# This is the sleep time for the spider in hours
spider_sleep_time: 6 

# This is the rss feed URLs of all the sites
feed_urls:
  fox_news: https://api.foxsports.com/v2/content/optimized-rss?partnerKey=MB0Wehpmuj2lUhuRhQaafhBjAJqaPU244mlTDK1i&size=30
  life_hacker: https://lifehacker.com/feed/rss